// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2B3mJiSEfc4_kv1m-pEVk4OaVFP28hdY',
    appId: '1:1092639561657:android:d05c31961fb3976bb50868',
    messagingSenderId: '1092639561657',
    projectId: 'skill-drills-haden',
    storageBucket: 'skill-drills-haden.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtLRvFyp196jN2UdpLbfdnaFPhIpoZ3sY',
    appId: '1:1092639561657:ios:c802363d812a4526b50868',
    messagingSenderId: '1092639561657',
    projectId: 'skill-drills-haden',
    storageBucket: 'skill-drills-haden.appspot.com',
    androidClientId: '1092639561657-b0n4esdigf696jqbm60nqfmvnq4c1qcf.apps.googleusercontent.com',
    iosClientId: '1092639561657-op99ucesokvmb8srqr6tqblkdibjiltc.apps.googleusercontent.com',
    iosBundleId: 'com.example.skilldrills',
  );
}
